-- Shared calendar snapshot table for all admin users.
create table if not exists public.calendar_snapshots (
  school_year text primary key,
  payload jsonb not null,
  version integer not null default 1 check (version > 0),
  updated_by text not null,
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_calendar_snapshot_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_calendar_snapshots_updated_at on public.calendar_snapshots;
create trigger trg_calendar_snapshots_updated_at
before update on public.calendar_snapshots
for each row
execute function public.set_calendar_snapshot_updated_at();

alter table public.calendar_snapshots enable row level security;

create table if not exists public.calendar_change_log (
  id bigint generated by default as identity primary key,
  school_year text not null,
  action text not null check (action in ('CREATE', 'UPDATE', 'CONFLICT_REJECTED')),
  actor_email text not null,
  base_version integer,
  new_version integer,
  changed_dates text[] not null default '{}',
  changed_fields text[] not null default '{}',
  change_summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_calendar_change_log_school_year_created_at
  on public.calendar_change_log (school_year, created_at desc);

create index if not exists idx_calendar_change_log_actor_email_created_at
  on public.calendar_change_log (actor_email, created_at desc);

alter table public.calendar_change_log enable row level security;

-- No policies by default. Tables are accessed only by server route with service role key.
